Repository TeamMascota/Mascota-iOS, pull requests merged in 2021-07, with the labels that each got.

#24 [#21] SwiftLint 경고문에 맞게 수정
  Mascota/Mascota/Sources/Extensions/UIColor+Extension.swift
Labels: dayzi, refactor

#23 #20 feat set navigation bar
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Constants/BookType.swift
  Mascota/Mascota/Resources/Storyboards/RainbowViewController.storyboard
  Mascota/Mascota/Sources/Extensions/UIString+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIView+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIViewController+Extension.swift
  Mascota/Mascota/Sources/View/BookPageView.swift
  Mascota/Mascota/Sources/View/CircleProfileButton.swift
  Mascota/Mascota/Sources/ViewControllers/BaseViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#27 #25 fix color and font
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Colors.xcassets/macoBlack.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoBlue.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoDarkGray.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoGray.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoIvory.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoLightGray.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoOrange.colorset/Contents.json
  Mascota/Mascota/Resources/Colors.xcassets/macoYellow.colorset/Contents.json
  Mascota/Mascota/Sources/Extensions/String+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIFont+Extension.swift
Labels: dayzi, fix

#30 [#28] MainNavigationBarView
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/View/CircleProfileButton.swift
  Mascota/Mascota/Sources/View/MainNavigationBarView.swift
  Mascota/Mascota/Sources/ViewControllers/BaseViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#32 [#14] 다크모드 비활성화, Status Bar Color Black으로 고정, Scene Delegate에서 RootViewController 설정
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Info.plist
  Mascota/Mascota/Resources/Storyboards/Base.lproj/Main.storyboard
  Mascota/Mascota/Resources/Storyboards/RainbowViewController.storyboard
  Mascota/Mascota/Sources/AppDelegate.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
Labels: dayzi, feat

#34 [#33] info.plist에 font 추가, SceneDelegate 수정, MainNavigationBar 수정
  Mascota/Mascota/Resources/Constants/BookType.swift
  Mascota/Mascota/Resources/Info.plist
  Mascota/Mascota/Sources/Extensions/UIFont+Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/MainNavigationBarView.swift
Labels: dayzi, fix

#35 [#18] rainbow view 레이아웃 완료
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/helpCard.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/helpCard.imageset/Group 166.png
  Mascota/Mascota/Resources/Constants/AppConstants.swift
  Mascota/Mascota/Resources/Constants/Constants.swift
  Mascota/Mascota/Sources/Cells/RainbowBookPageTableViewCell.swift
  Mascota/Mascota/Sources/Cells/RainbowButtonTableViewCell.swift
  Mascota/Mascota/Sources/Cells/RainbowHelpCardTableViewCell.swift
  Mascota/Mascota/Sources/Cells/RainbowHelpHeaderTableViewCell.swift
  Mascota/Mascota/Sources/MascotaUI/CircleProfileButton.swift
  Mascota/Mascota/Sources/MascotaUI/MacoButton.swift
  Mascota/Mascota/Sources/MascotaUI/MainNavigationBarView.swift
  Mascota/Mascota/Sources/View/BookContentView.swift
  Mascota/Mascota/Sources/View/BookPageView.swift
  Mascota/Mascota/Sources/View/BookRainbowPageView.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#37 [#36] 무지개 최고의 순간 뷰 구현
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/Cells/RainbowBookPageTableViewCell.swift
  Mascota/Mascota/Sources/Extensions/UINavigationController+Extension.swift
  Mascota/Mascota/Sources/MascotaUI/MacoButton.swift
  Mascota/Mascota/Sources/MascotaUI/RainbowNavigationBarView.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/RainbowBestSectionFooterView.swift
  Mascota/Mascota/Sources/View/RainbowBestSectionHeaderView.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBestViewController.swift
Labels: dayzi, feat

#40 [#39] 머지 후 오류 수정 및 폴더 추가
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Constants/AppConstants.swift
  Mascota/Mascota/Sources/Footers/RainbowBestSectionFooterView.swift
  Mascota/Mascota/Sources/Headers/RainbowBestSectionHeaderView.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
Labels: fix, soonsil

#43 #41 feat rainbow comment view
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/Extensions/String+Extension.swift
  Mascota/Mascota/Sources/View/BookPageView.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowCommentViewController.swift
Labels: dayzi, feat

#45 #44 feat rainbow book cover
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/Extensions/String+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIDevice+Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/BookCoverView.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBookCoverViewController.swift
Labels: dayzi, feat

#50 [#46] feat Raingbow Epilogue ViewController
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/Cells/RainbowBookPageTableViewCell.swift
  Mascota/Mascota/Sources/Cells/RainbowHelpCardTableViewCell.swift
  Mascota/Mascota/Sources/Extensions/String+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIButton+Extension.swift
  Mascota/Mascota/Sources/Extensions/UILabel+Extension.swift
  Mascota/Mascota/Sources/Extensions/UINavigationItem+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIStackView+Extension.swift
  Mascota/Mascota/Sources/Extensions/UITextField+Extension.swift
  Mascota/Mascota/Sources/Extensions/UITextView+Extension.swift
  Mascota/Mascota/Sources/MascotaUI/RainbowNavigationBarView.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowEpillogueViewController.swift
Labels: dayzi, feat

#56 [#54] feat use navigation bar
  Mascota/Mascota/Sources/Extensions/UINavigationController+Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBestViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBookCoverViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowCommentViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowEpillogueViewController.swift
Labels: dayzi, feat

#59 [#29] 주인공등록 뷰 1차 구현
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/btnIconBack.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnIconBack.imageset/btnIconBack.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconBack.imageset/btnIconBack@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconBack.imageset/btnIconBack@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconPlus.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnIconPlus.imageset/btnIconPlus.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconPlus.imageset/btnIconPlus@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconPlus.imageset/btnIconPlus@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuit.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuit.imageset/btnIconQuit.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuit.imageset/btnIconQuit@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuit.imageset/btnIconQuit@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuitDefaultGray.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuitDefaultGray.imageset/btnIconQuitDefaultGray.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuitDefaultGray.imageset/btnIconQuitDefaultGray@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnIconQuitDefaultGray.imageset/btnIconQuitDefaultGray@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/calendar1.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/calendar1.imageset/calendar1.png
  Mascota/Mascota/Resources/Assets.xcassets/calendar1.imageset/calendar1@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/calendar1.imageset/calendar1@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icCalendarFill.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icCalendarFill.imageset/icCalendarFill.png
  Mascota/Mascota/Resources/Assets.xcassets/icCalendarFill.imageset/icCalendarFill@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icCalendarFill.imageset/icCalendarFill@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icImg.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icImg.imageset/icImg.png
  Mascota/Mascota/Resources/Assets.xcassets/icImg.imageset/icImg@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icImg.imageset/icImg@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/yeonseo.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/yeonseo.imageset/yeonseo.png
  Mascota/Mascota/Resources/Assets.xcassets/yeonseo.imageset/yeonseo@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/yeonseo.imageset/yeonseo@3x.png
  Mascota/Mascota/Resources/Info.plist
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Sources/APIModels/RegisterMyPetAPIModel.swift
  Mascota/Mascota/Sources/Cells/MakePlusCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/MakePlusCollectionViewCell.xib
  Mascota/Mascota/Sources/Cells/RegisterMyPetCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/RegisterMyPetCollectionViewCell.xib
  Mascota/Mascota/Sources/Extensions/UIAlertAction+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIViewController+Extension.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterMyPetViewController.swift
Labels: feat, remi

#58 [#42] 목차 상세 뷰 초기 구현
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/delete.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/delete.imageset/group211.png
  Mascota/Mascota/Resources/Assets.xcassets/delete.imageset/group211@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/delete.imageset/group211@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/edit.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/edit.imageset/group210.png
  Mascota/Mascota/Resources/Assets.xcassets/edit.imageset/group210@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/edit.imageset/group210@3x.png
  Mascota/Mascota/Resources/Constants/AppConstants.swift
  Mascota/Mascota/Resources/Info.plist
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Sources/Cells/IndexDetailHeaderView.swift
  Mascota/Mascota/Sources/Cells/IndexDetailTableViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexDetailTableViewCell.xib
  Mascota/Mascota/Sources/Extensions/UIImage + Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
Labels: feat

#61 [#60] setBackgroundcolor 중복 제거
  Mascota/Mascota/Sources/Extensions/UIViewController+Extension.swift
Labels: fix, remi

#57 [#47] 목차 수정 뷰 구현
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Constants/AppConstants.swift
  Mascota/Mascota/Resources/Storyboards/IndexEdit.storyboard
  Mascota/Mascota/Sources/Cells/HomeIndexCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexEditCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexEditCollectionViewCell.xib
  Mascota/Mascota/Sources/Cells/IndexEditPrologueCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexEditPrologueCollectionViewCell.xib
  Mascota/Mascota/Sources/Cells/MascotaPeopleImageCell.xib
  Mascota/Mascota/Sources/Cells/PartCollectionViewCell.xib
  Mascota/Mascota/Sources/Extensions/String+Extension.swift
  Mascota/Mascota/Sources/Extensions/UIViewController+Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/CustomLabelAlertView.swift
  Mascota/Mascota/Sources/View/CustomLabelAlertView.xib
  Mascota/Mascota/Sources/View/CustomTextFieldAlertView.swift
  Mascota/Mascota/Sources/View/CustomTextFieldAlertView.xib
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
  Mascota/Mascota/Sources/ViewControllers/LoginViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: feat

#68 [#63] Register Prolog Book View and DoneMakingView
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/btnImgAddBookEmpty.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnImgAddBookEmpty.imageset/btnImgAddBookEmpty.png
  Mascota/Mascota/Resources/Assets.xcassets/btnImgAddBookEmpty.imageset/btnImgAddBookEmpty@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnImgAddBookEmpty.imageset/btnImgAddBookEmpty@3x.png
  Mascota/Mascota/Resources/Info.plist
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Resources/Storyboards/RegisterPrologBook.storyboard
  Mascota/Mascota/Sources/Extensions/UIButton+Extension.swift
  Mascota/Mascota/Sources/ViewControllers/DoneMakingBookViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterMyPetViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterPrologBookViewController.swift
Labels: feat, remi

#75 [#74] 탭바 기본 설정 및 Scene Delegate 수정
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/TabBarController/MacoTabBarController.swift
Labels: feat

#78 [#77] 모야 설정 완료
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/APIServices/APIService.swift
  Mascota/Mascota/Sources/MoyaPlugins/MoyaLogginPlugin.swift
Labels: feat

#80 [#79] KingFisher 설치 및 UIImageView Extension 추가
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/Extensions/UIImageView + Extension.swift
  Mascota/Podfile
  Mascota/Podfile.lock
Labels: feat

#76 [#71] feat calendar view
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall.png
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextSmall.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icNextSmall.imageset/icNextSmall.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextSmall.imageset/icNextSmall@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextSmall.imageset/icNextSmall@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Back.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Back.imageset/icNextX2Back.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Back.imageset/icNextX2Back@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Back.imageset/icNextX2Back@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Small.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Small.imageset/icNextX2Small.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Small.imageset/icNextX2Small@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icNextX2Small.imageset/icNextX2Small@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/icWriting.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icWriting.imageset/icWriting.png
  Mascota/Mascota/Resources/Assets.xcassets/icWriting.imageset/icWriting@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icWriting.imageset/icWriting@3x.png
  Mascota/Mascota/Sources/Cells/MacoCalendarCell.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Podfile
  Mascota/Podfile.lock
Labels: dayzi, feat

#72 [#69] 회원가입뷰, 로그인 뷰 수정 및 텍스트필드로직 구현
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/btnDoublecheck.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/btnDoublecheck.imageset/btnDoublecheck.png
  Mascota/Mascota/Resources/Assets.xcassets/btnDoublecheck.imageset/btnDoublecheck@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/btnDoublecheck.imageset/btnDoublecheck@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/group66.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/group66.imageset/group66.png
  Mascota/Mascota/Resources/Assets.xcassets/group66.imageset/group66@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/group66.imageset/group66@3x.png
  Mascota/Mascota/Resources/Storyboards/Login.storyboard
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Resources/Storyboards/RegisterPrologBook.storyboard
  Mascota/Mascota/Resources/Storyboards/SignUp.storyboard
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/DoneSignUpViewController.swift
  Mascota/Mascota/Sources/ViewControllers/LoginViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: fix, remi

#84 [#83] navigation controller 이슈 해결
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/TabBarController/MacoTabBarController.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowDiaryDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
  Mascota/Podfile.lock
Labels: dayzi, feat

#89 [#85] 목차 수정 뷰 서버 연결
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/APIModels/BriefDiaryModel.swift
  Mascota/Mascota/Sources/APIModels/ChapterMonthDiary.swift
  Mascota/Mascota/Sources/APIModels/DetailDiaryModel.swift
  Mascota/Mascota/Sources/APIModels/FirstPartMainModel.swift
  Mascota/Mascota/Sources/APIModels/GetChapterModel.swift
  Mascota/Mascota/Sources/APIModels/GetChapterPerMonthModel.swift
  Mascota/Mascota/Sources/APIModels/IndexModel.swift
  Mascota/Mascota/Sources/APIModels/TableContentsModel.swift
  Mascota/Mascota/Sources/APIServices/APIService.swift
  Mascota/Mascota/Sources/APIServices/ChapterAPI.swift
  Mascota/Mascota/Sources/Cells/IndexEditCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexEditPrologueCollectionViewCell.swift
  Mascota/Mascota/Sources/View/CustomTextFieldAlertView.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
Labels: feat

#91 [#81] 홈 서버 일부 연결
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Constants/AppConstants.swift
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Sources/APIModels/FirstPartMainModel.swift
  Mascota/Mascota/Sources/APIModels/HomeFirstPartModel.swift
  Mascota/Mascota/Sources/APIModels/SecondPartMainPageModel.swift
  Mascota/Mascota/Sources/APIServices/HomeAPI.swift
  Mascota/Mascota/Sources/Cells/HomeIndexCollectionViewCell.swift
  Mascota/Mascota/Sources/MascotaUI/MainNavigationBarView.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
Labels: feat

#93 [#90] feat rainbow server
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Constants/DateProcessing.swift
  Mascota/Mascota/Sources/APIModels/GetRainbowHomeModel.swift
  Mascota/Mascota/Sources/APIModels/HelpCardModel.swift
  Mascota/Mascota/Sources/APIModels/MemoryModel.swift
  Mascota/Mascota/Sources/APIModels/RainbowMainPageModel.swift
  Mascota/Mascota/Sources/APIServices/RainbowAPI.swift
  Mascota/Mascota/Sources/Cells/RainbowBookPageTableViewCell.swift
  Mascota/Mascota/Sources/Cells/RainbowHelpCardTableViewCell.swift
  Mascota/Mascota/Sources/View/BookRainbowPageView.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBestViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#96 [#94] feat rainbow bridge server
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Assets.xcassets/icAppWhite.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icAppWhite.imageset/icAppWhite.png
  Mascota/Mascota/Resources/Assets.xcassets/icAppWhite.imageset/icAppWhite@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icAppWhite.imageset/icAppWhite@3x.png
  Mascota/Mascota/Resources/Constants/EmojiStyle.swift
  Mascota/Mascota/Sources/APIModels/BookInfoModel.swift
  Mascota/Mascota/Sources/APIModels/DiaryModel.swift
  Mascota/Mascota/Sources/APIModels/GetRainbowMomentModel.swift
  Mascota/Mascota/Sources/APIModels/GetRainbowPetModel.swift
  Mascota/Mascota/Sources/APIModels/GetRainbowRecordModel.swift
  Mascota/Mascota/Sources/APIModels/PartingRainbowBridgeModel.swift
  Mascota/Mascota/Sources/APIModels/PetModel.swift
  Mascota/Mascota/Sources/APIModels/PutPartingRainbowBridge.swift
  Mascota/Mascota/Sources/APIModels/RainbowPetInfoModel.swift
  Mascota/Mascota/Sources/APIModels/TheBestModel.swift
  Mascota/Mascota/Sources/APIServices/RainbowAPI.swift
  Mascota/Mascota/Sources/Cells/RainbowBookPageTableViewCell.swift
  Mascota/Mascota/Sources/Extensions/UIBarButtonItem+Extension.swift
  Mascota/Mascota/Sources/Headers/RainbowBestSectionHeaderView.swift
  Mascota/Mascota/Sources/View/BookCoverView.swift
  Mascota/Mascota/Sources/View/BookRainbowPageView.swift
  Mascota/Mascota/Sources/View/CustomCollectionAlertView.swift
  Mascota/Mascota/Sources/View/ProfileNameButton.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBookCoverViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBridgeViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowMomentViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowRecordViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#99 [#92] 목차 상세 서버 통신 완료
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Sources/APIModels/ChapterMonthlyDiariesModel.swift
  Mascota/Mascota/Sources/APIModels/DetailDiaryModel.swift
  Mascota/Mascota/Sources/APIModels/GetChapterPerMonthModel.swift
  Mascota/Mascota/Sources/APIModels/IndexDetailModel.swift
  Mascota/Mascota/Sources/APIModels/MonthlyDiariesModel.swift
  Mascota/Mascota/Sources/APIServices/APIService.swift
  Mascota/Mascota/Sources/APIServices/ChapterAPI.swift
  Mascota/Mascota/Sources/APIServices/DiaryAPI.swift
  Mascota/Mascota/Sources/Cells/IndexDetailTableViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexDetailTableViewCell.xib
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
Labels: feat

#102 [#101] 리드미 수정
  README.md
Labels: docs

#105 [#104] feat rainbow moment detail diary view server
  Mascota/Mascota/Sources/APIModels/DiaryModel.swift
  Mascota/Mascota/Sources/APIModels/RainbowMainPageModel.swift
  Mascota/Mascota/Sources/APIServices/DiaryAPI.swift
  Mascota/Mascota/Sources/Cells/DiaryDetailImageCollectionViewCell.swift
  Mascota/Mascota/Sources/Extensions/UITextView+Extension.swift
  Mascota/Mascota/Sources/View/BookCoverView.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarDiaryDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowDiaryDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowMomentViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowRecordViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#107 [#100] 다이어리 작성 일부 완성
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Storyboards/DiaryWriteSecond.storyboard
  Mascota/Mascota/Sources/APIModels/PetImageModel.swift
  Mascota/Mascota/Sources/APIModels/PetsImageModel.swift
  Mascota/Mascota/Sources/APIServices/PetsAPI.swift
  Mascota/Mascota/Sources/AppModels/CharacterModel.swift
  Mascota/Mascota/Sources/AppModels/DiaryWriteModel.swift
  Mascota/Mascota/Sources/Cells/CharacterCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/PetEmotionCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/PetsCollectionViewCell.swift
  Mascota/Mascota/Sources/ViewControllers/DIaryWriteSecondViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DiaryWriteFirstViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
Labels: feat

#108 #86 fix register my pet cell logic
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Sources/APIModels/RegisterMyPetAPIModel.swift
  Mascota/Mascota/Sources/Cells/RegisterMyPetCollectionViewCell.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/CustomTextFieldAlertView.xib
  Mascota/Mascota/Sources/ViewControllers/DoneMakingBookViewController.swift
  Mascota/Mascota/Sources/ViewControllers/LoginViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterMyPetViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterPrologBookViewController.swift
Labels: fix, remi

#95 #87 feat sign up connect server
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Storyboards/IndexEdit.storyboard
  Mascota/Mascota/Resources/Storyboards/Login.storyboard
  Mascota/Mascota/Resources/Storyboards/SignUp.storyboard
  Mascota/Mascota/Sources/APIModels/RequestLoginModel.swift
  Mascota/Mascota/Sources/APIModels/RequestSignUpModel.swift
  Mascota/Mascota/Sources/APIModels/ResponseLoginModel.swift
  Mascota/Mascota/Sources/APIModels/ResponseSignUpModel.swift
  Mascota/Mascota/Sources/APIServices/AccountAPI.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/View/CustomLabelAlertView.xib
  Mascota/Mascota/Sources/ViewControllers/DoneSignUpViewController.swift
  Mascota/Mascota/Sources/ViewControllers/LoginViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: feat, remi

#109 [NON ISSUE] FIX Scene Delegate
  Mascota/Mascota/Sources/SceneDelegate.swift
Labels: fix

#113 #112 feat home book page view
  Mascota/Mascota/Sources/Cells/BookPageCollectionViewCell.swift
  Mascota/Mascota/Sources/View/BookHomePageView.swift
  Mascota/Mascota/Sources/View/BookWriteView.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
Labels: dayzi, feat

#115 [#100] 다이어리 작성 서버 통신 완료
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Sources/APIServices/DiaryAPI.swift
  Mascota/Mascota/Sources/AppModels/CharacterModel.swift
  Mascota/Mascota/Sources/AppModels/CharactersModel.swift
  Mascota/Mascota/Sources/AppModels/DiaryWriteModel.swift
  Mascota/Mascota/Sources/ViewControllers/DIaryWriteSecondViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DiaryWriteFirstViewController.swift
Labels: feat

#117 [#114] feat change image asset
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall.png
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/icBackSmall.imageset/icBackSmall@3x.png
  Mascota/Mascota/Resources/Assets.xcassets/illustHome.imageset/Contents.json
  Mascota/Mascota/Resources/Assets.xcassets/illustHome.imageset/illustHome.png
  Mascota/Mascota/Resources/Assets.xcassets/illustHome.imageset/illustHome@2x.png
  Mascota/Mascota/Resources/Assets.xcassets/illustHome.imageset/illustHome@3x.png
  Mascota/Mascota/Resources/Constants/BookType.swift
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Sources/Cells/MascotaPeopleImageCell.xib
  Mascota/Mascota/Sources/Cells/RainbowButtonTableViewCell.swift
  Mascota/Mascota/Sources/MascotaUI/CircleProfileButton.swift
  Mascota/Mascota/Sources/MascotaUI/MainNavigationBarView.swift
  Mascota/Mascota/Sources/TabBarController/MacoTabBarController.swift
  Mascota/Mascota/Sources/View/BookContentView.swift
  Mascota/Mascota/Sources/View/BookRainbowPageView.swift
  Mascota/Mascota/Sources/View/BookWriteView.swift
  Mascota/Mascota/Sources/View/DiaryDetailView.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowBridgeViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
Labels: dayzi, feat

#118 [#111] fix image asset
  Mascota/Mascota/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  Mascota/Mascota/Resources/Storyboards/Login.storyboard
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Resources/Storyboards/SignUp.storyboard
  Mascota/Mascota/Sources/Cells/MakePlusCollectionViewCell.xib
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/DoneMakingBookViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterMyPetViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterPrologBookViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: fix, remi

#122 [#119] feat connect detail diary view
  Mascota/Mascota/Resources/Storyboards/IndexDetail.storyboard
  Mascota/Mascota/Resources/Storyboards/IndexEdit.storyboard
  Mascota/Mascota/Sources/Extensions/UIBarButtonItem+Extension.swift
  Mascota/Mascota/Sources/Footers/RainbowBestSectionFooterView.swift
  Mascota/Mascota/Sources/View/BookContentView.swift
  Mascota/Mascota/Sources/View/BookWriteView.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowMomentViewController.swift
Labels: dayzi, feat

#123 [#120] Splash 화면 로티 적용
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  Mascota/Mascota/Resources/Storyboards/Splash.storyboard
  Mascota/Mascota/Resources/maco_logo.json
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/SplashViewController.swift
  Mascota/Mascota/Sources/ViewControllers/ViewController.swift
Labels: feat, remi

#121 [#116] 인디케이터 추가
  Mascota/Mascota.xcodeproj/project.pbxproj
  Mascota/Mascota/Resources/loading_block.json
  Mascota/Mascota/Sources/AppModels/IndicatorType.swift
  Mascota/Mascota/Sources/Extensions/UIViewController+Extension.swift
  Mascota/Mascota/Sources/ViewControllers/BaseViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
Labels: feat

#124 [#119] 홈뷰 - 일기상세보기뷰 연결
  Mascota/Mascota/Sources/View/BookContentView.swift
  Mascota/Mascota/Sources/View/BookHomePageView.swift
  Mascota/Mascota/Sources/View/BookWriteView.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
Labels: dayzi, feat

#127 [#125] 목록 - 다이어리 상세보기 뷰 연결
  Mascota/Mascota/Sources/Cells/IndexDetailTableViewCell.xib
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
Labels: dayzi

#129 [#128] 텍스트 필드 값 초과시 빨간색 숫자 표시
  Mascota/Mascota/Resources/Assets.xcassets/illustLoginsignupSmall.imageset/Contents.json
  Mascota/Mascota/Resources/Storyboards/RegisterMyPet.storyboard
  Mascota/Mascota/Resources/Storyboards/SignUp.storyboard
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterMyPetViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RegisterPrologBookViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: fix, remi

#130 [#126] 서버 통신 인디케이터 부착
  Mascota/Mascota/Sources/ViewControllers/CalendarDiaryDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/CalendarViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DIaryWriteSecondViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DiaryWriteFirstViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeDiaryDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
  Mascota/Mascota/Sources/ViewControllers/LoginViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowRecordViewController.swift
  Mascota/Mascota/Sources/ViewControllers/RainbowViewController.swift
  Mascota/Mascota/Sources/ViewControllers/SignUpViewController.swift
Labels: feat

#132 [#131] 버그 수정
  Mascota/Mascota/Sources/Cells/HomeIndexCollectionViewCell.swift
  Mascota/Mascota/Sources/Cells/IndexEditCollectionViewCell.swift
  Mascota/Mascota/Sources/Extensions/UINavigationController+Extension.swift
  Mascota/Mascota/Sources/SceneDelegate.swift
  Mascota/Mascota/Sources/ViewControllers/DIaryWriteSecondViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DiaryWriteFirstViewController.swift
  Mascota/Mascota/Sources/ViewControllers/HomeStartViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexDetailViewController.swift
  Mascota/Mascota/Sources/ViewControllers/IndexEditViewController.swift
Labels: fix

#135 [#133] 일기 작성 서버 통신 수정
  Mascota/Mascota/Sources/APIServices/DiaryAPI.swift
  Mascota/Mascota/Sources/AppModels/CharacterModel.swift
  Mascota/Mascota/Sources/AppModels/CharactersModel.swift
  Mascota/Mascota/Sources/ViewControllers/DIaryWriteSecondViewController.swift
  Mascota/Mascota/Sources/ViewControllers/DiaryWriteFirstViewController.swift
Labels: fix

#137 [#136] 라이브러리 추가
  Mascota/Mascota/Resources/Storyboards/DiaryWriteSecond.storyboard
  Mascota/Mascota/Sources/AppDelegate.swift
  Mascota/Podfile
  Mascota/Podfile.lock
Labels: feat
